# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='content_html',
            field=models.TextField(null=True),
        ),
    ]
