# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-14 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlemodel_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='public_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
