# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20170116_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
