# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmsuser',
            old_name='protrait',
            new_name='portrait',
        ),
    ]
