# -*- coding: utf-8 -*-
# @Author: Mack
# @Date:   2016-10-31 14:42:45
# @Last Modified by:   56958
# @Last Modified time: 2017-09-18 10:19:47
"""
Django settings for myblog project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vyz@m(rb$!6!n73vs7g()mtn1scv+p327yqyv4*v-%6u)wzmfw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.8.205.196','192.168.1.100','localhost','127.0.0.1','192.168.114.128','169.254.180.218']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.cms',
    'api.common',
    'api.front',
    'frontauth',
    'article',
    'cmsauth',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'frontauth.middlewares.AuthMiddleware'
]

ROOT_URLCONF = 'myblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'contextprocessor.cms_contextprocessor.CmsContextProcessor',
                'frontauth.context_processors.auth'
            ],
        },
    },
]

WSGI_APPLICATION = 'myblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'myblog',
        'USER': 'root',
        'PASSWORD': '582562324',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# CACHES
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': [
            '127.0.0.1:11211',
        ]
    }
}

# session
# 基于缓存的
# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

# 基于数据库的 （默认）
# SESSION_ENGINE = 'django.contrib.sessions.backends.db' 

# 基于文件的存储
# 一般用于网站小 没有数据库 
# SESSION_ENGINE = 'django.contrib.sessions.backends.file'
# SESSION_FILE_PATH = 'D:/django/'
 
# 基于数据库+缓存的  (用的比较多)
# 先写到缓存中 再同步到数据库 读取时优先从缓存中找  缓存没有  则到数据库中查找
# SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

# 浏览器一关闭，则session过期,无视`SESSION_COOKIE_AGE`
# SESSION_EXPIRE_AT_BROWSER_CLOSE=True



# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
LOGIN_URL = '/cms/login/'

# email config
EMAIL_HOST_PASSWORD = 'hauxjsfwvhxfbcbh'
EMAIL_HOST_USER = '569589854@qq.com'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_POST = 587
EMAIL_USE_TLS = True

# 设置每页放置文章篇数
NUM_PAGE = 15